### ISSUE TITLE
Sample Web

### ISSUE THREAD

**Issue by beatsm** [PeteGoo/Pushqa#7]
Stock Ticker sample no longer works!

**Comment by PeteGoo** [comment]
Thanks for reporting it. Seems good here. Can you give me more info? The WPF sample or the javascript one? Errors?

**Comment by beatsm** [comment]
Hi Peter,

Thanks for the response. I am trying to run the Stock Ticker example in VS 2012. When the page starts nothing happens. Even when I try unchecking the boxes nothing is displayed.

I don't see any errors.

Regards

**Comment by PeteGoo** [comment]
Hmmm, sounds a bit weird. Can you open the developer tools for your browser (press F12 for chrome) and check the console tab to see if there are any javascript errors?

**Comment by beatsm** [comment]
Hmm

No Javascript errors but I do have the following which explains why nothing is happening.

Don't know why though!

Failed to load resource: the server responded with a status of 400 (Bad Request) http://localhost:14844/events/Stocks//negotiate?%24filter=(Name+eq+'AMZN')+or+(Name+eq+'AAPL')+or+(Name+eq+'GOOG')+or+(Name+eq+'MSFT')&_=1371722800902

**Comment by IanYates** [comment]
I've just tried on my machine - seems to be behaving properly for me.  VS2012 (running as administrator - not tried as a non-admin although I don't see why it wouldn't work).  I've tried IE 10 and chrome whatever - both are happy.

Apart from JS errors are there any errors reported by VS in the output tab?  Is your VS set to stop on all exceptions?  If not, set it to do so in case there's some exception being raised that's going unnoticed.

**Comment by beatsm** [comment]
Thanks for your help, could not find any errors but looking at the url. I noticed a double // before negotiate.

changed var connection = $.connection('../events/Stocks/'); to var connection = $.connection('../events/Stocks');

All now works fine.

**Comment by PeteGoo** [comment]
Nice catch! The connection object comes from the SignalR jQuery extension. Might be worth raising over there.

**Comment by IanYates** [comment]
I saw your double / and dismissed it - serves me right for not knowing my javascript all that well.  Do you know why it affected you and not us?  (I'm very far from a javascript expert - my use of Pushqa at the moment is in the beginnings of a client/server ASP.Net / WPF app - C# top to bottom)

**Comment by beatsm** [comment]
No idea, I just grabbed the whole project and tried to run the examples as I think this would be good for real time Session Storage updates for items a user is interested in.

**Comment by PeteGoo** [comment]
I've removed the trailing slashes from the connection urls. Still seems to work fine so better be safe this way. Any objections?

**Comment by IanYates** [comment]
None from me :+1:

**Comment by beatsm** [comment]
Looks good to me with the new SignalR bits.
